// Stub — the real file is generated by 02-01 and will be merged before deployment.
// This file is created here to satisfy TypeScript in the parallel 02-02 worktree.

export type Attendee = {
  id: string
  swapcard_url: string
  first_name: string | null
  last_name: string | null
  company: string | null
  job_title: string | null
  career_stage: string | null
  biography: string | null
  expertise: string[] | null
  interests: string[] | null
  how_others_can_help: string | null
  how_i_can_help: string | null
  country: string | null
  seeking_work: boolean | null
  recruitment: string | null
  linkedin: string | null
  why_they_matter: string | null
  how_to_engage: string | null
  hypothesis: string | null
  risks: string | null
  collaboration_hooks: string | null
  created_at: string
  updated_at: string
}
